### PR TITLE
Update runner ver to 0.14.0

### PR DESCRIPTION
**Pull request by eugenekatsov**

### CODE REVIEW

**Comment by sauce-tartar** [comment]
Large number of package lock pins moving to accept update at patch.

Screen Shot 2022-10-31 at 3 00 41 PM

**Comment by eugenekatsov** [comment]
@sauce-tartar Thanks for the info. I agree that there are quite a few changes there that are unexpected. My guess is that the package.lock was generated quite a while ago, possibly before npm v6.0.0 Given the conversation here, it seems to me that this expected behavior: https://github.com/npm/npm/issues/20434#issuecomment-402988364

**Comment by sauce-tartar** [comment]
LTS stable standard packaging behaviour now, lets roll with it.

**Pros**

* smaller bundles (fewer patch hard pins in the tree)
* installs roll in patches

**Cons**

* affects *many* deps
* fluidity makes for more edge cases and harder to reproduce

**Mitigation**

Rolling a beta as well it gives a chance to catch any gnarly drift for those looking to give feedback.
You're bumping minor so rollback to pinned 0.13 is a fallback for those impacted.

**Comment by sauce-tartar** [comment]
@eugenekatsov what do you think about moving the CI Node and NPM version ahead to match the package lock era?

https://github.com/screener-io/screener-storybook/blob/f6589ea71668aa7c4b64441f2e750d39b65cecd4/.circleci/config.yml#L5

**Comment by sauce-tartar** [comment]
and this, zoinks

https://github.com/screener-io/screener-storybook/blob/f6589ea71668aa7c4b64441f2e750d39b65cecd4/.circleci/config.yml#L21

let me chip in a bit more here and take a look into that image ..

**Comment by sauce-tartar** [comment]
@eugenekatsov fyi going to forklift that image from:

```
node: v12.18.3
npm: 6.14.6
```

to Node 16 + NPM 8

Want this for the storeStoreV7 work as well, currently internal.

How many points to promote a super rare alpha release candidate image to `0.0.2` 😁 ?

**Comment by sauce-tartar** [comment]
Cancelling all that Circle CI suggested above, the docker image doesn't have anything more than the e2e in the repo, which is way behind Visual Tests now.

**Comment by sauce-tartar** [comment]
LGTM, all tests passing on Visual Tests for Staging and Prod 👍

**Pull request merged**
